pipeline {
  agent any

  environment {
    DOCKER_IMAGE = 'sayn78300/projet2-node-app'
    DOCKER_TAG = 'latest'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Sayn78/Projet2.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('app') {
          script {
            sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
          }
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        script {
          withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh """
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
            """
          }
        }
      }
    }
  }

  post {
    success {
      echo '✅ Image Docker buildée et poussée avec succès !'
    }
    failure {
      echo '❌ Échec du pipeline.'
    }
  }
}
