---
- name: Réinitialiser complètement Kubernetes
  hosts: k8s
  become: true
  tasks:
    - import_tasks: roles/k8s/tasks/reset_cluster.yml

- name: Préparer le runtime containerd
  hosts: k8s
  become: true
  roles:
    - containerd
  tags: containerd

- name: Installer Kubernetes sur la VM EC2
  hosts: k8s
  become: true
  roles:
    - k8s
  tags: install-k8s

- name: Initialiser le master Kubernetes
  hosts: k8s
  become: true
  vars:
    pod_network_cidr: "172.17.0.0/16"
  tasks:
    - import_tasks: roles/k8s/tasks/init_master.yml
      tags: init-master
      
- name: Vérifier que les composants de base tournent
  hosts: k8s
  become: true
  tasks:
    - import_tasks: roles/k8s/tasks/check_components.yml

- name: Déployer l'application Node.js sur Kubernetes
  hosts: k8s
  become: true
  tasks:
    - import_tasks: roles/k8s/tasks/deploy_app.yml
      tags: deploy-app
