---
- name: Installer Kubernetes sur la VM EC2
  hosts: k8s
  become: true
  roles:
    - k8s

- name: Initialiser le master Kubernetes
  hosts: k8s
  become: true
  tasks:
    - import_tasks: roles/k8s/tasks/init_master.yml
      tags: init-master
