---
- name: Désactiver le swap
  become: true
  ansible.builtin.command: swapoff -a

- name: Commenter les lignes de swap dans /etc/fstab
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*swap)'
    replace: '# \1'

- name: Créer le dossier pour les clés APT
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Ajouter la clé GPG de Kubernetes
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | \
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Ajouter le dépôt Kubernetes
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
    state: present

    filename: kubernetes

- name: Installer kubelet, kubeadm, kubectl
  become: true
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true


- name: Créer le dossier pour les manifests
  ansible.builtin.file:
    path: /home/ubuntu/k8s-manifests
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copier les fichiers YAML de l'application Node.js
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/ubuntu/k8s-manifests/"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - deployment.yaml
    - service.yaml
